In [5]:
# funcion len 
N= 'Milena' #cambiar 'tu nombre' por su verdadero nombre 
if len (N)>10:
  A="es un nombre muy largo"
else:
    A= "es un nombre muy corto"
print(N,A,sep="/")

Milena/es un nombre muy corto


In [7]:
# asignacion multiple 
a=3
b=4
area = a*b 
print(area)

12


In [8]:
#asignacion multiple
w,x,y,z,= "apple", "watermelon","grape", 28
print(w)
print(x)
print(y)
print(z)

apple
watermelon
grape
28


In [9]:
# reccorer los valores en un texo 
texto = "metodos numericos"
texto[0]

'm'

In [10]:
texto[5]

'o'

In [12]:
texto [-1] #ultimo caracter del texto  guardado en el "texto"

's'

In [13]:
texto[0:5]

'metod'

In [15]:
#listas 
listas=[7,7,7,7,5,5,5,5,2,2,2]

In [20]:
print(listas)

[7, 7, 7, 7, 5, 5, 5, 5, 2, 2, 2]


In [21]:
listas[3]

7

In [22]:
listas[1:4]

[7, 7, 7]

In [23]:
len(listas)

11

In [26]:
listas.append(23)

In [27]:
print(listas)

[7, 7, 7, 7, 5, 5, 5, 5, 2, 2, 2, 23]


In [28]:
 listas[0]=5

In [ ]:
print(listas)

In [39]:
print("antes", listas)
listas[0:2]=[]
print("despues", listas)

antes []
despues []


In [40]:
vector=[7,7,7,2,2,2,]

In [42]:
print("antes",vector)
vector[3:4]=[] #elimina el vector
print("despues", vector)

antes [7, 7, 7, 2, 2, 2]
despues [7, 7, 7, 2, 2]


tambien se  hacen listas, e conocen como arreglos y si todas las listas tiene la misma cantidad de elemntos las llamamos matrices.

In [43]:
lis=[[1,2,3],[4,5,6],[7,8,9]]
print(lis)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [44]:
lis[0]

[1, 2, 3]

In [45]:
lis[0][1]

2

In [46]:
lis[2][0]

7

# **Paquete numpy**
una matriz en python  se puede expresar como una listas. sin embargo, es preferible usal la funcion array del paquete *numpy* para poder hacer todo tipo de operaciones matriciales 
*   Escribimos primero
*   import numpy as np,
*   con el fin de llamar todas las funciones 






In [47]:
import numpy as np

In [49]:
np.array([[2,3,5],[6,7,8]])

array([[2, 3, 5],
       [6, 7, 8]])

In [51]:
D=np.array([[2,3,5],[6,7,8]])
D.shape   #tamaño de la matriz 

(2, 3)

In [52]:
D=np.array([[2,3,5],[6,7,8]])
D.size  #Cantidad de componentes  de la matriz  

6

In [57]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [58]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [61]:
np.identity(3)  #identidad es una matriz cuadrada 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])