In [2]:
# tipos de dato, string, entero, flotante, lista.

x='milena'
2* x

'milenamilena'

In [3]:
y= 'quiroga'

In [4]:
x + y

'milenaquiroga'

In [5]:
type (x) #el tipo de dato de la variable x es un string o cadena de caracteres 

str

In [6]:
z=8

In [7]:
type(z)

int

In [8]:
#int se inifica que es de tipo entero 

In [9]:
w=3.14

In [10]:
type(w)

float

In [11]:
#float que son numeros decimales 

In [12]:
entrada=input('ingrese un numero')

ingrese un numero45


In [13]:
type(entrada)

str

In [15]:
p = int(entrada)
print(p)

45


In [16]:
type (p)

int

In [17]:
k = float (entrada)

In [18]:
type(k)

float

In [19]:
k

45.0

Matrices con Numpy
Matrices.
Matrices
Igualdad entre matrices.
Suma y resta de matrices.
Multiplicación por escalar.
Multiplicación componente a componente de matrices.
Multiplicación real de matrices.
Transpuesta de una matriz.






In [21]:
import numpy as np  #np. es el que esta llamdo a la biblioteca numpy 


In [34]:
M=np.array([[4,5,6],[7,8,9]])
M

array([[4, 5, 6],
       [7, 8, 9]])

# Igualdad de matrices 

dos matrices son iguales si son iguales componentes a componente 

In [28]:
 j=np.array([[4,5,6],[7,-8,9]])
 j

array([[ 4,  5,  6],
       [ 7, -8,  9]])

In [33]:
M == j

array([[ True,  True,  True],
       [ True, False,  True]])

In [35]:
A=np.array([[1,-2,3],[4,1,-6],[7,4,2]])
B=np.array([[5,2,-3],[1,-1,2],[3,1,4]])

In [36]:
A

array([[ 1, -2,  3],
       [ 4,  1, -6],
       [ 7,  4,  2]])

In [37]:
B

array([[ 5,  2, -3],
       [ 1, -1,  2],
       [ 3,  1,  4]])

In [42]:
A[1][2]  #posicion (1,2) de la matriz A recuerde que se cuenta desde 0



-6

In [43]:
A [:,2] #se obtiene la columna 3 

array([ 3, -6,  2])

In [44]:
A[1] # es la fila uno de la matriz A es decir la segunda fila de la mtriz 

array([ 4,  1, -6])

#Traspuesta de una matriz 
sea $A$ una matriz, la matriz traspuerta de $A$ es
la matriz que se obtiene al intercambiar filas por 
columnas de la matriz $A$

In [49]:
# transpuesta de una matriz
print('la matriz A es: \n',A)
print('la matriz transpuesta es: \n',np.transpose(A))

la matriz A es: 
 [[ 1 -2  3]
 [ 4  1 -6]
 [ 7  4  2]]
la matriz transpuesta es: 
 [[ 1  4  7]
 [-2  1  4]
 [ 3 -6  2]]


#Suma y muestra de matrices 
la suma de matirces del mismo tamaño 


In [51]:
A

array([[ 1, -2,  3],
       [ 4,  1, -6],
       [ 7,  4,  2]])

In [52]:
B

array([[ 5,  2, -3],
       [ 1, -1,  2],
       [ 3,  1,  4]])

In [53]:
A+B  #suma de matrices 

array([[ 6,  0,  0],
       [ 5,  0, -4],
       [10,  5,  6]])

In [56]:
A-B #resta de matrices 

array([[-4, -4,  6],
       [ 3,  2, -8],
       [ 4,  3, -2]])

In [58]:

A*B # este producto es componente a componente .sin embargo NO es la mutiplicacion de matrices 

array([[  5,  -4,  -9],
       [  4,  -1, -12],
       [ 21,   4,   8]])

In [57]:
# la multiplicacion real de matrices se hace con @
A@B #multiplicacion de matrices 

array([[ 12,   7,   5],
       [  3,   1, -34],
       [ 45,  12,  -5]])

In [59]:

np.e #el numero de Euler

2.718281828459045

In [61]:
round(np.pi) # La funcion round aproxima a el entero mas cercano 

3

In [62]:
round(4.99)

5

In [63]:
round(np.e,5) # Aproxima el numero e a 5 cifras decimales 

2.71828

In [64]:
round(np.pi,10)

3.1415926536

Matrices Inversas
Si una matriz cuadrada  $A$  de $ n×n$   se multiplica por derecha e izquierda por una matriz  $B$  y se obtiene la identidad en ambos casos, es decir
                         $ AB=BA=In $  
La matriz $ B $ se conoce como el inverso multiplicativo de la matriz $ A $
 o más comunmente como la matriz inversa de  $A$ .

No todas las matrices cuadradas tienen inversa, la forma de determinarla empleando Python es meduante la función np.linalg.inv



In [72]:
D= np.array ([[1,2],[3,4]])
inv=np.linalg.inv (D)
inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [77]:
D= np.array ([[1,2,3],[0,4,5],[0,1,2]])
inv=np.linalg.inv (D)
inv

array([[ 1.        , -0.33333333, -0.66666667],
       [ 0.        ,  0.66666667, -1.66666667],
       [ 0.        , -0.33333333,  1.33333333]])

In [79]:
D@inv #comprobacion

array([[ 1.00000000e+00,  5.55111512e-17, -2.22044605e-16],
       [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [71]:
D =np.array([[1,2],[3,4]])
inversa=np.array([[-2,1],[1.5,-0.5]])

In [69]:
D@inversa

array([[1., 0.],
       [0., 1.]])

# Determinante de una matriz 
el determinate de una matriz $A$ es un numero real asociado a la matriz que perimite determinar si una matriz es invertible o no lo es.

Una matriz $A$ es invertible si solamnte si su determinante es distinto de cero.

En otras palabras una matriz $A$ es **singular** si su determinate es cero.

Utilizamos el comando **np.linag.det(nombre de matriz) ** para calcular el determiante

In [82]:
c=np.array([[1,2],[3,4]])
np.linalg.det (c)

-2.0000000000000004

In [84]:
C1 =np.array([[10,8],[5,4]])
np.linalg.det (C1)


0.0